//! Common error definitions.
use std::error;
use std::result;

/// A result returned by a driver operation.
pub type Result<A> = result::Result<A, Error>;

/// An error generated by a driver operation.
#[derive(Debug, Fail)]
pub enum Error {
    /// An error originating from the I2C bus.
    #[fail(display = "I2C error: {}", error)]
    I2C {
        /// The underlying I2C error.
        error: Box<error::Error + Send + Sync>,
    },
}
